### Lab2. Design of Logic Gates using Perceptron and Keras

## Part-1  Design OR gate using the concept of Perceptron

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    y=1/(1+(np.exp(-x)))
    return y    

In [3]:
def logic_gate(w1, w2, b): 
 # Helper to create logic gate functions 
 # Plug in values for weight_a, weight_b, and bias
     return lambda x1, x2: sigmoid(w1 * x1 + w2 * x2 + b) 


In [4]:
def test(gate): 
 # Helper function to test out our weight functions.
 for a, b in (0, 0), (0, 1), (1, 0), (1, 1): 
         print("{}, {}: {}".format(a, b, np.round(gate(a,  b)))) 

In [5]:
or_gate = logic_gate(20, 20, -10) 
test(or_gate) 


0, 0: 0.0
0, 1: 1.0
1, 0: 1.0
1, 1: 1.0


## Part-2   Implement the operations of AND, NOR and NAND gates

### Step-1

In [6]:
#AND gate
and_gate = logic_gate(10, 10, -10) 
test(and_gate)

0, 0: 0.0
0, 1: 0.0
1, 0: 0.0
1, 1: 1.0


### Step-2

In [7]:
#NAND GATE
nand_gate = logic_gate(-1,-1,2) 
test(nand_gate)

0, 0: 1.0
0, 1: 1.0
1, 0: 1.0
1, 1: 0.0


### Step-3

In [8]:
#NOR GATE
nor_gate = logic_gate(-1,-1,1) 
test(nor_gate)

0, 0: 1.0
0, 1: 0.0
1, 0: 0.0
1, 1: 0.0


## PART-3  Limitations of single neuron for XOR operation

In [9]:
def test1(gate): 
 # Helper function to test out our weight functions.
 for a, b in (1, 0), (0, 0), (0, 0), (0, 1): 
         print("{}, {}: {}".format(a, b, np.round(gate(a,  b)))) 

In [10]:
xor_gate = logic_gate(-2,-2,1) 
test1(xor_gate)

1, 0: 0.0
0, 0: 1.0
0, 0: 1.0
0, 1: 0.0


## PART-4 Logic Gates using Keras Library

In [11]:
from keras.models import Sequential
from keras.layers.core import Dense

### AND gate

In [12]:
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

target_data = np.array([[0],[0],[0],[1]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.2300 - binary_accuracy: 0.7500 - 914ms/epoch - 914ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2293 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2286 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2279 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2272 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2265 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2258 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2251 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2244 - binary_accuracy: 0.7500 - 0s/epoch - 0s/step
Epoch 10/100
1/1 - 0s - loss: 0.2238 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2231 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2224 - binary_accuracy: 0.750

Epoch 97/100
1/1 - 0s - loss: 0.1660 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1653 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1646 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1639 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
1/1 [==============================] - 0s 165ms/step
[[0.]
 [0.]
 [0.]
 [1.]]


### OR gate

In [13]:
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

target_data = np.array([[0],[1],[1],[1]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
 optimizer='adam',
 metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.1969 - binary_accuracy: 1.0000 - 679ms/epoch - 679ms/step
Epoch 2/100
1/1 - 0s - loss: 0.1961 - binary_accuracy: 0.7500 - 15ms/epoch - 15ms/step
Epoch 3/100
1/1 - 0s - loss: 0.1953 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 4/100
1/1 - 0s - loss: 0.1945 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 0.1938 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 6/100
1/1 - 0s - loss: 0.1930 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 7/100
1/1 - 0s - loss: 0.1922 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 8/100
1/1 - 0s - loss: 0.1914 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 9/100
1/1 - 0s - loss: 0.1907 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 10/100
1/1 - 0s - loss: 0.1899 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 11/100
1/1 - 0s - loss: 0.1892 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 12/100
1/1 - 0s - loss: 0.1885 - binary_accuracy: 0

Epoch 97/100
1/1 - 0s - loss: 0.1400 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1396 - binary_accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1392 - binary_accuracy: 0.7500 - 7ms/epoch - 7ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1388 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
1/1 [==============================] - 0s 94ms/step
[[1.]
 [1.]
 [1.]
 [1.]]


### NAND gate

In [14]:

training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

target_data = np.array([[1],[1],[1],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
 optimizer='adam',
 metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.2721 - binary_accuracy: 0.5000 - 661ms/epoch - 661ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2713 - binary_accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2706 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2698 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2691 - binary_accuracy: 0.7500 - 16ms/epoch - 16ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2683 - binary_accuracy: 0.7500 - 16ms/epoch - 16ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2676 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2669 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2661 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2654 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2647 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2640 - binary_accurac

Epoch 97/100
1/1 - 0s - loss: 0.2230 - binary_accuracy: 0.5000 - 8ms/epoch - 8ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2225 - binary_accuracy: 0.5000 - 8ms/epoch - 8ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2221 - binary_accuracy: 0.5000 - 24ms/epoch - 24ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2216 - binary_accuracy: 0.5000 - 8ms/epoch - 8ms/step
1/1 [==============================] - 0s 86ms/step
[[1.]
 [1.]
 [0.]
 [1.]]


### NOR gate

In [17]:
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

target_data = np.array([[1],[0],[0],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.2931 - binary_accuracy: 0.0000e+00 - 566ms/epoch - 566ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2919 - binary_accuracy: 0.0000e+00 - 12ms/epoch - 12ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2908 - binary_accuracy: 0.0000e+00 - 16ms/epoch - 16ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2896 - binary_accuracy: 0.0000e+00 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2885 - binary_accuracy: 0.0000e+00 - 48ms/epoch - 48ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2873 - binary_accuracy: 0.0000e+00 - 8ms/epoch - 8ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2863 - binary_accuracy: 0.0000e+00 - 8ms/epoch - 8ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2852 - binary_accuracy: 0.0000e+00 - 8ms/epoch - 8ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2841 - binary_accuracy: 0.0000e+00 - 0s/epoch - 0s/step
Epoch 10/100
1/1 - 0s - loss: 0.2831 - binary_accuracy: 0.0000e+00 - 8ms/epoch - 8ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2821 - binary_accuracy: 0.0000e+00 - 0s/epoch - 0s/step
Epoch 12/100


Epoch 96/100
1/1 - 0s - loss: 0.2167 - binary_accuracy: 0.7500 - 0s/epoch - 0s/step
Epoch 97/100
1/1 - 0s - loss: 0.2161 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2154 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2148 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2141 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
1/1 [==============================] - 0s 96ms/step
[[0.]
 [0.]
 [0.]
 [0.]]


### X-OR gate

In [15]:
training_data = np.array([[1,0],[0,0],[0,0],[0,1]], "float32")

target_data = np.array([[0],[1],[1],[0]], "float32")

model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
 optimizer='adam',
 metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.2460 - binary_accuracy: 0.2500 - 654ms/epoch - 654ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2456 - binary_accuracy: 0.2500 - 11ms/epoch - 11ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2452 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2447 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2443 - binary_accuracy: 0.7500 - 6ms/epoch - 6ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2439 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2434 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2430 - binary_accuracy: 0.7500 - 16ms/epoch - 16ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2426 - binary_accuracy: 0.7500 - 8ms/epoch - 8ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2422 - binary_accuracy: 0.7500 - 0s/epoch - 0s/step
Epoch 11/100
1/1 - 0s - loss: 0.2417 - binary_accuracy: 0.7500 - 0s/epoch - 0s/step
Epoch 12/100
1/1 - 0s - loss: 0.2413 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.2078 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2075 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2071 - binary_accuracy: 1.0000 - 0s/epoch - 0s/step
Epoch 100/100
1/1 - 0s - loss: 0.2067 - binary_accuracy: 1.0000 - 8ms/epoch - 8ms/step
1/1 [==============================] - 0s 99ms/step
[[0.]
 [1.]
 [1.]
 [0.]]
